### ISSUE TITLE
repkit evt skadesystem på bil

### ISSUE THREAD

**Issue by voodoo97** [nidarosrp/bugreport#100]
hei jeg har forsøkt å reparere bilene mine x antall ganger etter restarten og det funka veldig dårlig men før i dag funker det fjell dere må prøve å få tatt en titt på det

**Comment by kenneiv90** [comment]
Hva mener du med at det ikke fungerer ?

**Comment by voodoo97** [comment]
e fikk brukt det og den ryker 1 min seinere og jeg har kjørt pent og hele pakka alt funka fint før restart
