### ISSUE TITLE
Dopsalg fungerer ikke etter oppdatering

### ISSUE THREAD

**Issue by xToxicRainmanx** [nidarosrp/bugreport#102]
Når man prøver å selge kokain til lokale, går det alltid inn melding til politiet. har prøvd å selge rund 50 ganger nå, å har ikke fått solgt noe. litt vanskelig å tjene penger når det ikke fungerer.

**Comment by kenneiv90** [comment]
Dette er ikke en bug. Det er gjort vanskeligere å selge.
