### ISSUE TITLE
Taxi lokalt bug

### ISSUE THREAD

**Issue by Repori** [nidarosrp/bugreport#103]
Når jeg skal plukke opp lokale, så løper lokalene bort til taxien og ser på den og fryser. Dette skjer flere ganger iløpet av dagen. Du har litn sjangs for at de du plukker opp setter seg inn i bilen.

Mulig og få fikset? 

-Sjef av taxi: Alex

**Comment by ProJB** [comment]
Det får vi ikke fikset, og er lagt inn i scriptet.

Men, er taxien fungerende?

**Comment by Repori** [comment]
Ja taxien er fungerende ellers. Har funnet ut at de taxibilene er det galt med. Så vi må ordne nye biler til taxien :)

Men det kan vell ordnes i RP?

**Comment by kenneiv90** [comment]
Denne skal være løst
