### ISSUE TITLE
Larry's Auto

### ISSUE THREAD

**Issue by JonasKarlsen** [nidarosrp/bugreport#105]
Låsene på dørene inn til kontoret virker ikke de står ulåst er dette en bug eller en feil som kan rettes opp i vil gjerne ha lås på dørene inn til kontoret slik at det er kun vi som er ansatt på Larry's som har tilgang på kontoret.

**Comment by kenneiv90** [comment]
Da er det lagt inn dørlås på dørene på larrys. Kommer på neste update
