### ISSUE TITLE
Mbu kjøretøy, lager og Uniform

### ISSUE THREAD

**Issue by nitramlol** [nidarosrp/bugreport#106]
Hei. I dag skulle jeg ta på uniformen. Men verken jeg eller Pernille fikk opp menyen. Den var der et millisekund så forsvant den. Vi prøvde flere ganger. Det samme skjedde også med Menyen for Lager. Så vi fikk ikke tatt ut eller inn bandasjer og medkits. Jeg kunne heller ikke se Den røde sirkelen til Ambu parkeringen så jeg kunne ikke ta ut bilen min. Men pernille kunne se og ta ut sin. Hvorfor jeg ikke kunne se den, det vet jeg ikke. Lageret og uniformen fungerer heller ikke i Nord.

**Comment by kenneiv90** [comment]
Skal være fikset.
