### ISSUE TITLE
bensinstation ved meca sør

### ISSUE THREAD

**Issue by wow19954** [nidarosrp/bugreport#108]
Hei idag så har jeg opplevd en bug. var i nærheten av en pumpe for å fylle og brått går den bare opp i luften uten at jeg har vært borti den på noen som helst måte

**Comment by ProJB** [comment]
Hei.

Er et kjent bug, derfor mange velger å unngå den.

**Comment by kenneiv90** [comment]
Denne får vi ikke gjort noe med.
