### ISSUE TITLE
Garasjeproblemer

### ISSUE THREAD

**Issue by ReyMorgenstern** [nidarosrp/bugreport#110]
Hei

Problem 1: Når jeg av og til tar ut bilen fra garasjen, blir kameraet låst som om jeg fremdeles er i menyen for å velge bil, men kan løpe rundt, og kjøre rundt som normalt, men kameraet blir stuck. Funker ikke å skifte med V, eller noe annet for å komme seg ut av det, og må restarte.

Problem 2: Når jeg satt bilen inn, var den vinrød med gul perlelakk. Når jeg tar samme bilen ut igjen, så er den kun vinrød. Litt dumt da jeg virkelig likte den fargekombinasjonen :)

**Comment by nitramlol** [comment]
Hadde samme problemet. Har video. Men får bare sendt som bilde. OM vide ønskes så kan den bli sendt på Discord. Bilde link her: https://gyazo.com/1d643bbab4e7b40feb4af5c65fc745db

**Comment by kenneiv90** [comment]
Dette er en bug vi vet om. Garasjen vil bli byttet ut. Så denne bugen vil ikke bli utbedret.
