### ISSUE TITLE
Dop / Narkotika

### ISSUE THREAD

**Issue by MarZNOR** [nidarosrp/bugreport#23]
Markus Steinhoy
05.04.2020

Fant en fullt fungerende dop lab, men den funker ikke

![Desktop Screenshot 2020 04 05 - 15 08 46 37](https://user-images.githubusercontent.com/63166385/78499181-7e1a5c80-774f-11ea-8f7a-b371e21495d3.png)
![Desktop Screenshot 2020 04 05 - 15 08 41 63](https://user-images.githubusercontent.com/63166385/78499183-807cb680-774f-11ea-8ea0-ed468311c370.png)
![Desktop Screenshot 2020 04 05 - 15 08 37 63](https://user-images.githubusercontent.com/63166385/78499189-8377a700-774f-11ea-9dd4-ad4c9897104e.png)

**Comment by ProJB** [comment]
Uhm, ja...Altså... Da må man finne ingrediensene for å starte den opp? Eller?
