### ISSUE TITLE
Bahamas West

### ISSUE THREAD

**Issue by Aks1natorr** [nidarosrp/bugreport#24]
Butikk er kjøpt, men kan ikke gå inn i butikken, det er stengt. Megler mener det ikke skal kunne kjøpe denne plassen? Her må det en oppklaring til

**Comment by TheAirbourne7** [comment]
Dørene er ikke låst opp, derfor kommer man ikke inn. En låsesmed skal få åpnet dørene i natt.

Dere bør prøve å lage en avtale med meglern med tanke på at dere har betalt 1,2milloner for den

**Comment by Aks1natorr** [comment]
Megleren sier at de ikke kan gjøre noe med dette, vi øsnker å heve kjøpet, og få refundert kjøpesum 
1 310 000 om jeg ikke tar helt feil

**Comment by TheAirbourne7** [comment]
Megleren har fått instruksjon på hva de skal gjøre i saken, så det blir løst opp i

**Comment by TheAirbourne7** [comment]
Saken er da løst, pengene tilbakebetalt
