### ISSUE TITLE
Biler - Hast - Deler forsvinner

### ISSUE THREAD

**Issue by ProJB** [nidarosrp/bugreport#28]
Store problemer med at deler på biler forsvinner.

*De er satt inn i garasjen
*Det er kjøpte biler
*MECA opplever dette selv på sine egne biler

Vurderer kompensasjon for MECA som gir reklamasjon på dette.

**Comment by NoMaDJohansen** [comment]
Har det skjedd noe her? har mista alt som var gjort av tuning på bilen min, pluss perlemor fargen forsvinner.
Dette skulle vore gjort noe med kjapt.

**Comment by ProJB** [comment]
Hei.

Utviklerteamet har sett på det og justert noe i configfilen til bilene som ble med over fra "v1" - Det skal ha blitt lagt inn i nattens oppdatering. Si gjerne i fra hvis problemet vedvarer, det handler om feilsøking.

Mvh
Ole
