### ISSUE TITLE
#36 mistet alt invtory

### ISSUE THREAD

**Issue by Bestisline** [nidarosrp/bugreport#30]
#36 
Var i steinskjer å plukket skrapmetall, det kom en person bort å prata. Kunne ikke høre han så relogget. Våknet opp på sykehuset, da var inventory var slettet.  
Mistet: 
-54 k 
-34 rep kits 
-200 glassfiber

**Comment by TheAirbourne7** [comment]
dette gjelder da #36 på disc?

**Comment by Bestisline** [comment]
Ja
