### ISSUE TITLE
Leiligheter - Nye plasser

### ISSUE THREAD

**Issue by ProJB** [nidarosrp/bugreport#37]
Det trengs nye lokalisasjoner oppe i Stjørdal og Steinkjer.

Levanger Flyplass, der har Omega i avtale med Megler (Baxxx97) kjøpt campingvognen bak hangar og mangler "motellrom" ;)

<3

**Comment by ProJB** [comment]
Stjørdal ferdig. ca 60 leiligheter.

**Comment by ProJB** [comment]
Levanger ferdig. ca 35 leiligheter.

**Comment by kenneiv90** [comment]
Lagt til i arbeidsliste
