### ISSUE TITLE
Jobb-nav

### ISSUE THREAD

**Issue by Landgangogiste** [nidarosrp/bugreport#40]
Jobb-Nav
Står at man kan jobbe hos kommunen hos nav. når man skriv /jobb så kommer det opp '' du jobber hos - Kommunen - byplanlegger'' 
Jobb-nav
Man kan annsette seg som mekaniker hos nav, når man skriver /jobb så kommer det opp ''Du jobber som: Mekaniker - Mekaniker'' Men den skal ikke være der

**Comment by kenneiv90** [comment]
Takk for informasjon. Kommune jobben var en feil. Men mekaniker er en whitelisted jobb
