### ISSUE TITLE
Bil

### ISSUE THREAD

**Issue by Aks1natorr** [nidarosrp/bugreport#44]
Kjøpte en bil av typen RangeRover Evoqe. Denner er blitt fjernet, og replaced med en "baller". Hva er grunn til dette?

**Comment by ProJB** [comment]
Range Rover Evoqe var en replace av en annen bil, den er nå fjernet fra serveren. 

Gi meg prisen du la ut for Range Rover Evoqe, og finn prisen på nåværende Baller, så dekker i tapet.

Mvh
Administrasjonen.

**Comment by Aks1natorr** [comment]
Aha, det er for så vidt greit :) Hvordan er mulighetene for å levere inn bilen? og få det totalt refundert? Og heller kjøpe en bil jeg vil ha^^ :P

**Comment by ProJB** [comment]
Hei.

Ta bilen ned til bilforhandler, lever den på baksiden der, notèr beløpet du får så dekker vi resten.

Mvh
Administrasjonen

**Comment by Aks1natorr** [comment]
<3 dåkker e nr. 1!
