### ISSUE TITLE
Bilsalg

### ISSUE THREAD

**Issue by Aks1natorr** [nidarosrp/bugreport#45]
Får ikke muligheten til å selge bil ved bilbutikken. Både meg og Kristian Olsen har prøvd

**Comment by ProJB** [comment]
Hei.

Ok, er vel ingen som har prøvd å selge det før. Det blir ført opp som bug.
Hvis du kan skrive det totale beløpet på bilen og legg ved bilnr, så fikser vi resten.

**Comment by ProJB** [comment]
@actstorm

Jeg har fikset dette.
