### ISSUE TITLE
Mulig bug ved innlogging etter maintanence 

### ISSUE THREAD

**Issue by Gostrex** [nidarosrp/bugreport#52]
Vet ikke om det kvaliviserer som en bugg, eller om det er jeg som logger for sent ut når det er maintanence, men har hendt 2 ganger nå at jeg har logga ut på vakt fullt ikledd jobb klærne men når jeg logget inn igjen etterpå havnet litt langt unna (1gang) og i sivil klær men fremdeles på vakt (2 ganger). Ønsket bare si ifra om det. Men ellers er jeg knall fornøyd med oppsettet av serveren. Å knall bra spillere å RPe med..

**Comment by kenneiv90** [comment]
Har du slettet cache ?

**Comment by Gostrex** [comment]
Kan prøve å se om det hjelper :)

søn. 12. apr. 2020, 20:28 skrev Kenneth Iversen <notifications@github.com>:

**Comment by ProJB** [comment]
Status?

**Comment by Gostrex** [comment]
Jeg har slettet cache, slettet krasj filer opp til flere ganger logget ut å inn, quittet steam å startet det igjen flere ganger. Og det skjer enda.

**Comment by Gostrex** [comment]
Status på denne skjer enda. Jeg er fremdeles på vakt når jeg logger inn etter Restart. Men er ikledd sivile klær, Det har ikke skjedd at jeg har blitt teleportert. Kan det være noe jeg gjør galt, Jeg har til nå å logge ut ved å bruke "F8" -> quit, ett par minutter før server går ned.

**Comment by kenneiv90** [comment]
Dette kan være synkroniserings problem. Lagt til på arbeidslisten og vil bli sjekket.
