### ISSUE TITLE
Taxibug

### ISSUE THREAD

**Issue by ReyMorgenstern** [nidarosrp/bugreport#53]
Er et par "feil" med taxien.

1. Av og til når en får en NPC-kunde, kan den plutselig besvime, og forsvinne. Det er plagsomt når det endelig dukker opp en kunde, og den forsvinner slik. Er det slik den skal være?

2. Når en får en NPC-kunde, kjører bort til den, så begynner den å løpe bort mot taxien, for så å stoppe, og ikke bevege seg i det hele tatt. Med andre ord, det blir en kunde en ikke får kjørt rundt. Har innimellom fått kjøre kunder, men vil si at 60% har blitt slik som denne.

**Comment by ProJB** [comment]
Hei!

1. Ja, går det for lang tid så mister kunden interessen, utvikler skal se på det, men blir lagt inn på en arbeidsliste.

2. Bruker du privatbil eller bedriftsbil? Det kan være et problem som kan løses, men det er usikkert. Utvikler legger det inn :)

Mvh
Administrasjonen

**Comment by ReyMorgenstern** [comment]
1. Dette er snakk om at jeg rekker å snu taxien, og så "besvimer" kunden. Så må være utrolig utålmodige kunder :)

2. Går bare ann med NPC-kunder i bedriftsbilen, så er den jeg kjører rundt med

**Comment by ProJB** [comment]
Hei,

Takk for svar. Det er notert ned.

2. Det er mulig å "cheate" det systemet, er derfor jeg spør :)

Mvh
Administrasjonen

**Comment by ReyMorgenstern** [comment]
Vel, ikke vet jeg hvordan det er mulig å "cheate" det systemet, og ikke vil jeg vite det heller. :) Men får bare spørre mer hvis det trengs :)
