### ISSUE TITLE
Får ikke godt på vakt i Ambulansen

### ISSUE THREAD

**Issue by Gostrex** [nidarosrp/bugreport#57]
Når jeg logget meg inn på serveren nå, å skulle til å gå på vakt i Ambuen så gikk det ikke. fikk ikke opp "Gå av/på" vakt teksten.

**Comment by TheAirbourne7** [comment]
Fikset

**Comment by Gostrex** [comment]
Det kom tilbake i dag, samme bug, etter å ha slettet cache og krasj filer, logget ut å inn av steam 3 ganger, logget ut og inn av spillet 6 ganger ga jeg opp å kjørte rundt litt og RPet av vakt:) fikk gjort det jeg skulle uansett :) så får jeg se om det vedvarer i morgen.

**Comment by Gostrex** [comment]
Fant ut at jeg vistnok spawna for nær jobben. Gikk helt fint i dag når jeg spawna på torget.
