### ISSUE TITLE
Mulig bugg med Ambulanse script

### ISSUE THREAD

**Issue by Gostrex** [nidarosrp/bugreport#62]
Jeg får ikke brukt Gjennoppliv, små sår, alvårlige skader og Putt inn i Ambulanse. (Jeg har jobb som ambulanse), men kommer opp ingen borgere i nærheten, når jeg tydelig ser spilleren rett ved meg, Andre spillere ser spilleren en annen plass, jeg prøver der også men samme svar. Ingen spillere i nærheten. Dette har skjedd meg hver gang jeg har kjørt ut på oppdrag.

**Comment by ProJB** [comment]
Hei,

Har du utstyr med deg? Medkits, firstaid og bandasjer med deg? 
Det er noen ganger at spilleren er andre plasser, det er et synk-problem fra FiveM sin side.

Mvh
Pro

**Comment by Bestisline** [comment]
Flere i ambulansen sliter med at de ikke ser pasienter når de kommer fram til stedet. Beskjed fra Arya

**Comment by TheAirbourne7** [comment]
Ambuen klarte ikke å finne meg de heller

**Comment by Gostrex** [comment]
Status på denne: (tre ting)
1. Når jeg ankommer åstedet så ser jeg pasienten på min skjerm, men kan ikke bruke noen av alternativene på "f6 menyen" da det kommer opp ingen borgere i nærheten. På en annen spillers skjerm er Pasienten på en annen plass, og på pasientens skjerm er dem en annen plass enn det igjen.
2. Jeg ankommer stedet og ser ikke pasienten i det hele.
3. Alt går bra, og jeg kan bruke 1 av tingene på "f6 menyene", men om jeg bruker noen av de andre skjer det forsatt at jeg får opp ingen borger i nærheten. (skjedd 1 gang)
