### ISSUE TITLE
Ny karakter

### ISSUE THREAD

**Issue by Landgangogiste** [nidarosrp/bugreport#64]
Når man lage en ny karrakter så får man NR til den adnre karrateren opp på den nye.
Og hvis man eie en bolig så får man boligen fra den andre karrakteren over på den ny karrakteren

**Comment by ProJB** [comment]
Hei.

Det er et kjent problem, bare unngå å bruke leilighet. Vedr. kontaktene så lønner det seg å gjøre om navnene i listen til for eksempel:

Odin Borr, til [1]Odin Borr. Da vet du at dette er til karakter 1, og ikke karakter 2.
