### ISSUE TITLE
Taxi priser

### ISSUE THREAD

**Issue by NoMaDJohansen** [nidarosrp/bugreport#7]
Sette opp taxi prisene til max/min 1750/350.

mangen lange turer som burde vore bedre betalt siden det er mye kjøring av lokale folk, blir andre priser på spillere.

**Comment by ProJB** [comment]
Taxipriser blir justert til MIN: 150 og MAX 450 - Bensinpriser går ned for å balansere dette ut, så overvåkes dette i en ukes tid.

**Comment by Aks1natorr** [comment]
Taxipriser bør settes opp noe for at det skal være lukrativt å drive, og jobbe
