### ISSUE TITLE
Lønn/Skattesystem

### ISSUE THREAD

**Issue by Aks1natorr** [nidarosrp/bugreport#72]
God aften :) Forstod det slik at lønn til kommuneansatte skal komme av det som trekkes inn i skatt? 
Det bør sjekkes opp i dette systemet, da det ikke har dukket opp noe på konto de 4 dagene jeg har hatt jobben.

Det er også ønskelig med et lager på kommunekontoret, og mulighet til å sende faktura

**Comment by kenneiv90** [comment]
Hva skal du fakturere ?

**Comment by kenneiv90** [comment]
Du kan gjerne få faktura mulighet men da mister du støtte fra skattesystemet
