### ISSUE TITLE
Får ikke solgt bil

### ISSUE THREAD

**Issue by xNeverWeak** [nidarosrp/bugreport#73]
Hei, jeg får ikke solgt guardian bilen bak bilforhandleren i sentrum. Enten så er bilen for høy eller for stor til å komme nær den plassen jeg kan selge. Burde være en lett fiks med å høyne "area" eller flytte det litt ut sånn at man kan selge den. 

Takk :)

**Comment by kenneiv90** [comment]
Du får ikke solgt guardian til en bilforhandlern i sentrum.
