### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by xNeverWeak** [nidarosrp/bugreport#75]
Når jeg kom inn i byen fikk jeg beskjed at jeg hadde logget ut elns mens jeg var død. Fikk det ikke helt med meg. Så sto det - av ALT i inventory.
Jeg spawnet inn på sykehuset. Så logget jeg ut igjen, når jeg da kom tilbake på serveren. Så kom jeg tilbake der jeg logget ut

Skulle gjerne hatt tinga tilbake :D

**Comment by ProJB** [comment]
Hei.

Noterer du ned alt du har mistet her? Trenger det for arkivet sin skyld, da med HEX id også.

Mvh
Ole

**Comment by xNeverWeak** [comment]
Switchblade
1100+ Metall
1100+ sikringer
1300+ plastikk
550 +- glassfiber
Tlf
Radio*
Bandasje
30 bomull
60 skrapmetall
8500 kr
Brød / Vann, ca 10 av hver

Det er nok mer, men husker ikke alt

**Comment by ProJB** [comment]
Da er alt fikset.
