### ISSUE TITLE
Banshee 900R

### ISSUE THREAD

**Issue by NoMaDJohansen** [nidarosrp/bugreport#81]
Spille mitt krasjer en god del med denne bilen etter eg kjøpte den, veit ikke hva som er buggen med den med er bra lei av det problemet, går det ann å eventuelt få solgt den tilbake til den prisen eg kjøpte den for? Ganske plagsomt å ha bil til 1,4 mill som krasjer spillet mitt heile tiden.

**Comment by ProJB** [comment]
Hei.

Vi skal se om det finnes en annen fiks på dette.
