### ISSUE TITLE
Pengane mine er vekke

### ISSUE THREAD

**Issue by NoMaDJohansen** [nidarosrp/bugreport#84]
alle mine penger er vekke i løpet av natten, gikk med 1 980 684kr på meg å hadde 15 000kr på konto, i dag har eg ingen penger på meg å har 105 000kr i minus på kontoen, skulle egentlig sette alt i banken i går eller i dag siden banken har vert stengt så var det litt vanskelig.

**Comment by ProJB** [comment]
Actstorm tar en titt på dette siden han styrer skattesystemet.

kjøpte ikke du bil for pengene?

**Comment by kenneiv90** [comment]
lagt tilbake pengene

**Comment by NoMaDJohansen** [comment]
Takker <3
