### ISSUE TITLE
Bil forsvant

### ISSUE THREAD

**Issue by NoMaDJohansen** [nidarosrp/bugreport#85]
Entity2
skilt nr: KC 24254

kjøpte bilen, fikk skilt nr å slikt men den kom ut som lokal bil, får ikke satt den i garasjen, noen som kan sjekke dette?

**Comment by ProJB** [comment]
Bilen står nå på Torget.
Sjekk garasjen og gi tilbakemelding.

Mvh
ProJB

**Comment by NoMaDJohansen** [comment]
Den var i garasjen nå :) Litt merkelig at den feilen skjedde, men heldigvis så har bilforhandleren alle skilt nr lagra som dem selger ut :) Takk for hjelpen Ole :)
