### ISSUE TITLE
Mistet ting fra inventory etter nylig restart

### ISSUE THREAD

**Issue by Repori** [nidarosrp/bugreport#86]
Æ hadde 3000 meth på mæ, og brukte 4000kr på aluminiums folje. serveren restarta og æ mista alt av det æ hadde samla, hadde ikke pengan æ brukte, ikke meth, ikke aliminiums folje heller.

**Comment by ProJB** [comment]
Hei.

Jeg skal se  på dette men får ikke gjort noe uten ditt karakternavn ingame eller hexid. 
Og om du har noe form for bilde av inventory også, ville det ha hjulpet.

**Comment by Repori** [comment]
Heter Alex Kristiansen, in-game. 
HexID: 11000010e79c9d0

Har ikke noe bilde fra inventory, er litt fersk så er ikke vant med at sånne typer crash skjer.

Men takk for svar og hjelp! :)

**Comment by ProJB** [comment]
Hei.

Jeg refunderer 4 000,- på alu-folie. 
Narkotika refunderes ikke siden det ikke kan verifiseres og håper på forståelse der.

Mvh
ProJB

**Comment by Repori** [comment]
Tusen takk!
Setter stor pris på hjelpen!

Forstår at dopet ikke blir refundert, det går helt fint :)
