### ISSUE TITLE
Mulig Glitch/Bug i Skrot systemet

### ISSUE THREAD

**Issue by Gostrex** [nidarosrp/bugreport#87]
Når man leter etter skrot, så kan man sortere skrot i tillegg.. Og sortere flere kasser samtidig.. Usikker om dette er glitch/bug eller om det skal være slik at man skal få lov å gjøre dette.

En annen ting på samme er om man drikker vann mens man leter så kan man begynne å springe mens man enda "leter"

**Comment by ProJB** [comment]
Hei.

Jeg har satt en utvikler på jobben som skal se på det. 
Takk for tilbakemeldingen.

Mvh
Ole

**Comment by kenneiv90** [comment]
Dette er nok et problem vi ikke kan forhindre. Folk som velger å gjøre dette får bare gjøre det.
