### ISSUE TITLE
Politiet Problemer

### ISSUE THREAD

**Issue by Landgangogiste** [nidarosrp/bugreport#88]
Vi i Politet får ikke kjøpe skuddsikervest på stasjon etter siste server start.
Lure på om det e flytta en anna plass eller om man få skaffe det på andre måta no.
18:45 10.05.2020

**Comment by kenneiv90** [comment]
Det skal se på det

**Comment by kenneiv90** [comment]
Skal være fikset

**Comment by Landgangogiste** [comment]
Hvis det e fiksa, kor finn man der man kjøpe vesten? Fant ikke noe på stasjon før 20min siden

Sendt fra min iPhone
