### ISSUE TITLE
Får ikke overført / solgt Ambu (tjenestebiler)

### ISSUE THREAD

**Issue by Gostrex** [nidarosrp/bugreport#89]
Vi har hatt stort problem med at vi ikke for overført Tjenestebilene i Ambu, jeg prøvde sist i dag for å sjekke om det enda var ett problem. Så vi har mysta endel ambuer pga folk har slutta/blitt sparka av å ikke være på og blitt drept. Vet ikke helt hvorfor det ikke funker, kommer ikke opp noe feilmelding eller noe.

**Comment by kenneiv90** [comment]
Det er ikke mulig å  overføre arbeidsbiler enda. Men skal legge det til i listen min så vil det dukke opp på en oppdattering.
