### ISSUE TITLE
Fakturaer

### ISSUE THREAD

**Issue by tricer262** [nidarosrp/bugreport#90]
Hei
Er de mulig og få fjernet 5 fakturaer som eg har som eg ikkje skulle ha? Vegvesen sjefen, aria Black og reiley Johnson kan stadfeste de at dei skal eg ikkje ha hos meg siden eg allerede hadde lappen,
Mvh Thomas Sivertsen ingame

**Comment by Gostrex** [comment]
Det samme skjedde min karakter (Lasse), fikk ei rekning på 660 kr på han, men han har verken tatt eller kommer til å ta lappen. Å fikk beskjed om å snakke med SSV sjefen om det i RP.

**Comment by kenneiv90** [comment]
Hva er grunnen til at dere har fått regninger ?

**Comment by Gostrex** [comment]
Jeg sendte mld å spurte å fikk bare tilbare at det var for teorikurs eller
noe, noe som karakteren ikke har hatt noe av:s

lør. 16. mai 2020, 23:45 skrev Kenneth Iversen <notifications@github.com>:

**Comment by Gostrex** [comment]
Dette ble fikset av å snakke med sjefen i SSV.
