### ISSUE TITLE
Politibiler og sivilbiler

### ISSUE THREAD

**Issue by Grumpynorway** [nidarosrp/bugreport#94]
de burte tunes opp til en 250-260 og gjøres noe med grepe så de ikke er såpestykker på veien. har tatt dette med ole og han er enig i dette virkemidelet

**Comment by ProJB** [comment]
Støttes.

Uniformerte politibiler må justeres til 280 minst.
Sivil Police4 og FBI trenger også samme justering.

**Comment by kenneiv90** [comment]
Nye biler kommer fremover
