### ISSUE TITLE
Spøkelset på Mekonomen

### ISSUE THREAD

**Issue by MarZNOR** [nidarosrp/bugreport#97]
Det er da en Bug eller lignende i lo0kalet til mekonomen der man da blir kasta vegg imellom og mister HP / Blir downet, dette skjer titt og ofte. Man står bare i ro men så plutselig blir man kasta rett inn i veggen eller taket. Det har skjedd med flere personer inne på serveren, kan av og til skje andre plasser men hovedsaklig inne i bygget.

**Comment by Gostrex** [comment]
Dette skjer over hele serveren. Jeg har blitt downa eller mista mye liv pga dette både på politi stasjonen (avhørsrom), sykehuset i lobby opp til flere ganger, på skrapplassen helt oppi nord, og flere plasser. Ligner egentlig på noe alla det som skjer om man slapper folk eller noe.
